name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      uses: docker/build-push-action@v1
      with:
        dockerfile: Dockerfile
        push: false
