name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: docker/build-push-action@v1
      with:
        dockerfile: './app/Dockerfile'
        path: './app'
        push: false
